package main

var (
	attributes = map[string]Attribute{
		"str": {name: "Strength", abbreviation: "STR"},
		"dex": {name: "Dexterity", abbreviation: "DEX"},
		"con": {name: "Constitution", abbreviation: "CON"},
		"int": {name: "Intelligence", abbreviation: "INT"},
		"wis": {name: "Wisdom", abbreviation: "WIS"},
		"cha": {name: "Charisma", abbreviation: "CHA"},
	}

	groupCategories = map[string]GroupCategory{
		"vocation":    {name: "Vocation", attributeCount: 1},
		"affiliation": {name: "Affiliation", attributeCount: 1},
		"species":     {name: "Species", attributeCount: 2},
	}

	classes = map[string]Class{
		"deft": {
			name: "Deft",
			levels: map[int]Level{
				1: {
					xp:             0,
					hitDie:         1,
					bonusHitPoints: 0,
					attackValue:    10,
					savingThrow:    7,
					slotCount:      1,
					groupCount:     2,
					raiseCount:     0,
				},
				2: {
					xp:             1500,
					hitDie:         2,
					bonusHitPoints: 0,
					attackValue:    11,
					savingThrow:    8,
					slotCount:      1,
					groupCount:     2,
					raiseCount:     1,
				},
				3: {
					xp:             3000,
					hitDie:         2,
					bonusHitPoints: 1,
					attackValue:    11,
					savingThrow:    9,
					slotCount:      2,
					groupCount:     3,
					raiseCount:     1,
				},
				4: {
					xp:             6000,
					hitDie:         3,
					bonusHitPoints: 0,
					attackValue:    12,
					savingThrow:    10,
					slotCount:      2,
					groupCount:     3,
					raiseCount:     2,
				},
				5: {
					xp:             12000,
					hitDie:         3,
					bonusHitPoints: 1,
					attackValue:    12,
					savingThrow:    11,
					slotCount:      2,
					groupCount:     4,
					raiseCount:     2,
				},
				6: {
					xp:             24000,
					hitDie:         4,
					bonusHitPoints: 0,
					attackValue:    13,
					savingThrow:    12,
					slotCount:      2,
					groupCount:     4,
					raiseCount:     3,
				},
				7: {
					xp:             48000,
					hitDie:         4,
					bonusHitPoints: 1,
					attackValue:    13,
					savingThrow:    13,
					slotCount:      3,
					groupCount:     5,
					raiseCount:     3,
				},
				8: {
					xp:             96000,
					hitDie:         5,
					bonusHitPoints: 0,
					attackValue:    14,
					savingThrow:    14,
					slotCount:      3,
					groupCount:     5,
					raiseCount:     4,
				},
				9: {
					xp:             192000,
					hitDie:         5,
					bonusHitPoints: 1,
					attackValue:    14,
					savingThrow:    15,
					slotCount:      3,
					groupCount:     6,
					raiseCount:     4,
				},
				10: {
					xp:             384000,
					hitDie:         6,
					bonusHitPoints: 0,
					attackValue:    15,
					savingThrow:    16,
					slotCount:      4,
					groupCount:     6,
					raiseCount:     5,
				},
			},
		},
		"strong": {
			name: "Strong",
			levels: map[int]Level{
				1: {
					xp:             0,
					hitDie:         1,
					bonusHitPoints: 2,
					attackValue:    11,
					savingThrow:    5,
					slotCount:      1,
					groupCount:     2,
					raiseCount:     0,
				},
				2: {
					xp:             2000,
					hitDie:         2,
					bonusHitPoints: 0,
					attackValue:    11,
					savingThrow:    6,
					slotCount:      1,
					groupCount:     2,
					raiseCount:     1,
				},
				3: {
					xp:             4000,
					hitDie:         3,
					bonusHitPoints: 0,
					attackValue:    12,
					savingThrow:    7,
					slotCount:      1,
					groupCount:     2,
					raiseCount:     1,
				},
				4: {
					xp:             8000,
					hitDie:         4,
					bonusHitPoints: 0,
					attackValue:    13,
					savingThrow:    8,
					slotCount:      2,
					groupCount:     3,
					raiseCount:     2,
				},
				5: {
					xp:             16000,
					hitDie:         5,
					bonusHitPoints: 0,
					attackValue:    13,
					savingThrow:    9,
					slotCount:      2,
					groupCount:     3,
					raiseCount:     2,
				},
				6: {
					xp:             32000,
					hitDie:         6,
					bonusHitPoints: 0,
					attackValue:    14,
					savingThrow:    10,
					slotCount:      2,
					groupCount:     3,
					raiseCount:     3,
				},
				7: {
					xp:             64000,
					hitDie:         7,
					bonusHitPoints: 0,
					attackValue:    15,
					savingThrow:    11,
					slotCount:      3,
					groupCount:     4,
					raiseCount:     3,
				},
				8: {
					xp:             128000,
					hitDie:         8,
					bonusHitPoints: 0,
					attackValue:    15,
					savingThrow:    12,
					slotCount:      3,
					groupCount:     4,
					raiseCount:     4,
				},
				9: {
					xp:             256000,
					hitDie:         9,
					bonusHitPoints: 0,
					attackValue:    16,
					savingThrow:    13,
					slotCount:      3,
					groupCount:     4,
					raiseCount:     4,
				},
				10: {
					xp:             512000,
					hitDie:         10,
					bonusHitPoints: 0,
					attackValue:    17,
					savingThrow:    14,
					slotCount:      4,
					groupCount:     5,
					raiseCount:     5,
				},
			},
		},
		"wise": {
			name: "Wise",
			levels: map[int]Level{
				1: {
					xp:             0,
					hitDie:         1,
					bonusHitPoints: 1,
					attackValue:    10,
					savingThrow:    6,
					slotCount:      1,
					groupCount:     2,
					raiseCount:     0,
				},
				2: {
					xp:             2500,
					hitDie:         2,
					bonusHitPoints: 0,
					attackValue:    11,
					savingThrow:    7,
					slotCount:      1,
					groupCount:     2,
					raiseCount:     1,
				},
				3: {
					xp:             5000,
					hitDie:         2,
					bonusHitPoints: 1,
					attackValue:    11,
					savingThrow:    8,
					slotCount:      2,
					groupCount:     2,
					raiseCount:     1,
				},
				4: {
					xp:             10000,
					hitDie:         3,
					bonusHitPoints: 0,
					attackValue:    11,
					savingThrow:    9,
					slotCount:      2,
					groupCount:     3,
					raiseCount:     2,
				},
				5: {
					xp:             20000,
					hitDie:         4,
					bonusHitPoints: 0,
					attackValue:    12,
					savingThrow:    10,
					slotCount:      3,
					groupCount:     3,
					raiseCount:     2,
				},
				6: {
					xp:             40000,
					hitDie:         4,
					bonusHitPoints: 1,
					attackValue:    12,
					savingThrow:    11,
					slotCount:      3,
					groupCount:     3,
					raiseCount:     3,
				},
				7: {
					xp:             80000,
					hitDie:         5,
					bonusHitPoints: 0,
					attackValue:    12,
					savingThrow:    12,
					slotCount:      4,
					groupCount:     4,
					raiseCount:     3,
				},
				8: {
					xp:             160000,
					hitDie:         6,
					bonusHitPoints: 0,
					attackValue:    13,
					savingThrow:    13,
					slotCount:      4,
					groupCount:     4,
					raiseCount:     4,
				},
				9: {
					xp:             320000,
					hitDie:         6,
					bonusHitPoints: 1,
					attackValue:    13,
					savingThrow:    14,
					slotCount:      5,
					groupCount:     4,
					raiseCount:     4,
				},
				10: {
					xp:             640000,
					hitDie:         7,
					bonusHitPoints: 0,
					attackValue:    13,
					savingThrow:    15,
					slotCount:      5,
					groupCount:     5,
					raiseCount:     5,
				},
			},
		},
	}

	languages_ = []string{
		"Low Imperial",
		"High Imperial",
		"Khadish",
		"Selan",
		"Varlish",
		"Veton",
		"Fae",
		"Grimmark",
		"Draconic",
	}

	speciess = []Species{
		{"Human", 0.8},
		{"Dwarf", 0.2},
	}

	vocations_ = []string{
		"Armiger",
		"Thief",
		"Oracle",
		"Priest",
		"Butcher",
		"Smith",
	}

	affiliations_ = []string{
		// Religion & magic
		"Seekers of the Unknown Fire",
		"Church of the New Sun",
		"Witch Cult",
		"Spear of Cold-Eye",
		// Magic
		"Unseeing Monks",
		"Wardens of the Crystal Tower",
		"Star Watchers",
		// Nobles
		"Great House vet-Doranar",
		"Great House vet-Elvan",
		"Great House vet-Haan",
		"Low House vet-Aldar",
		"Low House vet-Akash",
		// Retinues & mercenaries
		"Foremost Armigers",
		"Black Dogs",
		"Order of the Sphinx",
		"Sulfur Company",
		"Aldred's Two Hundred",
		"Barrett's Privateers",
		// Tribes
		"Scrivenwood Varlings",
		"Crystal Lake Tribe",
		"Silver Mountain Tribe",
		"Smoldering Heart Tribe",
		// Guilds
		"Explorers' Guild",
		"Guild of Torturers",
		"Crimson Court",
		// Gangs
		"White Cloaks",
		"Wicker Men",
		"Fog Walkers",
	}

	attunements_ = []string{
		// Items
		// People
		// Animals
		// Locations
		"Caverns of Zakhar",
		"Silver Mountain",
		"Crystal Lake",
		"Scrivenwood",
		"Isolate Tower",
		"Scarred Glacier",
	}

	abilities_ = []string{
		"Ability 1: Protect ally",
		"Ability 2: Push attack",
		"Ability 3: Climb big enemy",
		"Ability 4: Battle frenzy",
		"Ability 5: Tactical command",
		"Ability 6: Encourage",
		"Ability 7: Double-attack",
		"Ability 8: Parry",
	}

	miracles_ = []string{
		// Witch King, ice, & darkness
		"Witch King's Blessing",
		"Witch King's False Life",
		"Icy Hand of the Witch King",
		"Invigorate the White Curse",
		"Banish to the Black Glass Labyrinth",
		"Blood to Ice",
		"Witchfrost Simulacrum",
		"Rolling Calf's Burning Eyes",
		"Tongue of He Who Speaks Sideways",
		"Resonance of Heart Bone",
		"Curse of Two-Tongues",
		"Baron's Walk Between Worlds",
		"Un-Fire of Akarbalas",
		"Rage of Red Wife",
		// Sun Goddess, stars, & fire
		"Sun Goddess's Blessing",
		"Invoke the First Fire",
		"Invoke the Second Fire",
		"Invoke the Third Fire",
		"Invoke the Fourth Fire",
		"Seek the Unknown Fire",
		"Sun's Cleansing Fire",
		"Cold-Eye's Gaze",
		"Shield of the Valkyrie Star",
		"Horn of the Huntress Star",
		"Bite of the Serpent Star",
		"Pluck from the Firmament",
		"Shift Constellations",
		"Starsong",
		"Silver Moonlight",
		// New Sun & light
		"New Sun's Blessing",
		"New Sun's Radiance",
		"New Sun's Fire",
		"Sanctifying Light",
		"Inquisition of the Dawn",
		"Dawn's Hallowing",
		"Concealment of the Dusk",
		"Dusk's Bane",
		"Twilight Shadowstep",
		// Air and wind
		"Freezing North Wind",
		"Blistering South Wind",
		"Soothing West Wind",
		"Tempestuous East Wind",
		"Message on the Breeze",
		// Animals
		"Call of the Elk",
		"Skin of the Bear",
		"Blackspider Venom",
		"Wisdom of the White Wyrm",
		// Plants
		"Acorn of Far Travel",
		"Oakform",
		"Treemeld",
		"One With Roots",
		"Leafsong",
		"Lay of the Last Sunflower",
		// Demons & hell
		"Sacred Seal",
		"Sixth-Circle Demonfire",
		"Fourth-Circle Hellfrost",
		"Marduk's Profane Gift",
		// Polymorph
		"Tentacle Arm",
		"Retractable Claws",
		"Winged Feet",
		// Blood magic
		"Mutagenic Blood",
		"Sanguinomancy",
		// Necromancy & disease
		"Part the Veil",
		"Create Revenant",
		"Banshee Scream",
		"Ghost Form",
		"Flense",
		"Sever Soul",
		// Electricity, metal, & magnetism
		"Magnetic Resonance",
		"Touch of Iron",
		"Riddle of Steel",
		"Thermometallurgy",
		// Earth
		"Deep One Sunders the Earth",
		"Crystal Adornment",
		// Battle
		"Vehk's Poem of Blades",
		"Ayem's Warpaint",
		"Seht's Battle-Sight",
		"Sword-Saint's Blessing",
		// Other
		"Amplify Noise",
		"Healing Water",
		"Magical Tattoo",
		"Curious Potion",
		"Explosive Runes",
	}
)
